### ISSUE TITLE
Contao 4 kompatibel

### ISSUE THREAD

**Issue by csaeum** [richardhj/contao-newsletter2go-sync#2]
Ist die Version schon Contao4 ready?

Bis wann kann man damit rechnen?

**Comment by richardhj** [comment]
Diese/Nächste Woche.

**Comment by csaeum** [comment]
Danke gerade installiert und werde es heute Abend mal testen.

Musste aber die minimale Stabilität auf "dev" setzen.

Für alle bei denen es sich erstmal nicht  installieren lässt

**Comment by richardhj** [comment]
Version 2.1 --> Contao 4 und PHP 7.2

**Comment by kikmedia** [comment]
Puh, ist libsodium dabei in Stein gemeisselt? Es gibt doch _einige_ Hoster, die das nicht aktiv haben :-(

**Comment by richardhj** [comment]
@kikmedia die Komponente wird verwendet, um den Auth-Key verschlüsselt abzulegen.
Wie du weißt, ist die `Encryption`-Klasse von Contao deprecated. Contao selbst verweist auf OpenSSL und phpseclib. Ich hatte mich damals umgeschaut, und herausgelesen, dass libsodium eigentlich Teil des Cores von PHP7.2 ist. Stimmt wohl nicht?!
Grundsätzlich kann die Komponente ausgetauscht werden, ich wüsste jetzt aber nicht, welcher weg der beste ist. Ist OpenSSL auf jeden Fall besser verfügbar?

**Comment by kikmedia** [comment]
OpenSSL sollte doch eigentlich immer und überall verfügbar sein. Zu libsodium heute der Hoster des Grauens: https://twitter.com/carolinakoehn/status/1090906671222800384

Mir ist auch nicht klar warum man das wegkonfiguriert.

Andere Hoster kann ich jetzt nicht sagen, vielleicht gibt es jemanden mit weiteren Erfahrungen?

**Comment by ghost** [comment]
@kikmedia 

LOL! Als ich "Hoster des Grauens" gelesen habe, kam mir ganz spontan Hosteurope in den Sinn und siehe da: Was für eine Überaschung!

Cyon hat es nach meiner Anfrage aktiviert. Weiss aber nicht, ob global oder nur auf dem Agencyserver.

**Comment by kikmedia** [comment]
Nachtrag: Nicht verfügbar auf Hosteurope sowie bei Mittwald. Beide sind nicht bereit es zu aktivieren.

@richardhj Soll ich ein Ticket für eine OpenSSL-Unterstützung aufmachen?

**Comment by richardhj** [comment]
Ja, mach mal :-)

**Comment by kikmedia** [comment]
See https://github.com/richardhj/contao-newsletter2go-sync/issues/5#issue-429091717
