### ISSUE TITLE
cURL error 7: Failed to connect to api.newsletter2go.com port 443

### ISSUE THREAD

**Issue by ghost** [richardhj/contao-newsletter2go-sync#3]
Hi

I've installed v2.1.x-dev with Contao 4.4.30. So far so good.

The Authentification fails with the following internal server error message:

_cURL error 7: Failed to connect to api.newsletter2go.com port 443: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)_

And the Log messages (changed the real domain name to xyz):

_[2019-01-19 19:57:52] request.INFO: Matched route "contao_backend". {"route":"contao_backend","route_parameters":{"_scope":"backend","_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\BackendController::mainAction","_route":"contao_backend"},"request_uri":"https://xyz/contao?do=newsletter2go_users&id=1&key=authenticate&ref=2p-5XX1R&rt=tHkMldgwgeZ3pTixtf6qz3_HvRa4we1qEbeuyaVPKFI","method":"POST"} []
[2019-01-19 19:57:52] security.INFO: Attempting SimplePreAuthentication. {"key":"backend","authenticator":"Contao\\CoreBundle\\Security\\ContaoAuthenticator"} []
[2019-01-19 19:57:52] app.CRITICAL: An exception occurred. {"exception":"[object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 7: Failed to connect to api.newsletter2go.com port 443: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) at /home/xyz/public_html/dev/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185)"} []_

Well, the api key and alle the other information should be correct and all the requirements are installed. Curl (7.6) is enabled in php 7.2. I have no idea about the cause.

Thanks for your support, Richard!

**Comment by richardhj** [comment]
Hi @DanEi75,

well that cURL error looks like a server constraint? Maybe some kind of firewall on the server? You can double check the error if you run your website on your local machine.

However, I found some other error in my test.
So if you can rid of the cURL error, and another error ("Missing client_id") persists, please follow these changes: richardhj/oauth2-newsletter2go#2

**Comment by ghost** [comment]
Hi @richardhj 

Thank you very much for your quick reply and the adjustment!
Well, a server issue was my first thought as well. I'm going to check it locally as soon as possible and give you a feedback during this week.

**Comment by ghost** [comment]
Hi @richardhj 

It works - almost ;-)! Now, I could authenticate and set a Newsletter2Go group to a new member group. Fine!

Unfortunately, the sync doesn't seem to work. I have one recipient in the Newsletter2Go group (in Newsletter2Go!). After group sync, this recipient doesn't appear. No error message.

I tried to define a member in Contao and set this one to the synced member group. But I couldn't save it because the following error message appears:

Type error: Argument 1 passed to Richardhj\Newsletter2Go\Contao\SyncBundle\Dca\Member::determineAttributeType() must be of the type array, null given, called in /home/selegerm/public_html/pro/vendor/richardhj/contao-newsletter2go-sync/src/Dca/Member.php on line 240

Sorry, I know, it's an alpha version, but I need this function quite badly.

**Comment by richardhj** [comment]
alpha doesn't mean it should not be runnable.
Is fixed in 3b8a81738b18ff4999172c261b5b6f82c15c27f0. Please update.

**Comment by DanEi75** [comment]
Hallo @richardhj 

Danke für Update. Gerade getestet. Klappt nicht beim Anlegen eines neuen Benutzers. Folgende Fehlermeldung: 

Call to a member function getHttpClient() on null.

Paar Zeilen tiefer gibt es übrigens noch einen kleinen Fehler: case 'chkecbox':

**Comment by ghost** [comment]
Fehler taucht nicht mehr auf. Weitere Fehlermeldungen unter: #4
