### ISSUE TITLE
newsletter2Go auth. error leads to php

### ISSUE THREAD

**Issue by quaxim-01n** [richardhj/contao-newsletter2go-sync#6]
Hello, I became newsletter2Go recommended (instead Mailchimp) also for data security reasons, but other than MC to get the first steps done seems much more complicated, got a little help from Contao-forum, since the Contao-Manager was not so "automatic" right in the beginning

Contao 4.4
- installed newsletter2Go "^2.0@alpha"
- entered API in Contao Backend
- when I try "authorization" I get an error, have no templates, no "Content" above in the Backend, 
auth. gives me:
> Type error: Argument 1 passed to Haste\Form\Form::addToTemplate() must be an instance of FrontendTemplate, instance of Contao\FrontendTemplate given, called in /www/htdocs/w01915e7/beate-meier.ch/vendor/richardhj/contao-newsletter2go-sync/src/Dca/Newsletter2GoUser.php on line 149

what exactly should I change in Line 149, HOW should it look? Actual unchanged line:
` $form->addToTemplate($userAuthTemplate);`

Thanks in any case and kind regards!

**Comment by richardhj** [comment]
I opened an issue in codefog/contao-haste#146.

**Comment by quaxim-01n** [comment]
Sorry I have to ask so stupid, I am not used to github, pretty new here and with "deeper" language. Will there be an update for the extension sometime (what is the "final info"?), or am I supposed to copy paste from the ticket #146?

I just landed here, because I could not find any helpful option in the contao community, documentation and N2Go offers still only Contao 3 plugin... Also no guide how to manually implement subscribe/unsubscribe (without autom. tampate) with N2Go...

Tank you all.

**Comment by richardhj** [comment]
When you update the packages, the issue should be resolved.

> Also no guide how to manually implement subscribe/unsubscribe (without autom. tampate) with N2Go...

All you need is a subscription form? Then I would rather include a form provided by Newsletter2Go.

**Comment by quaxim-01n** [comment]
I am sorry to bug here, but i don't get it. When I uploaded the Mailchimp extension I could simply validate the account and had a "module-type" to work with. I now updated the N2Go extension, I CAN validate now with the API, but still have nothing to implement and connect with Mate theme, for my frontend, no module at all, no template (which I surely could modify then), no starting point...
Contao 4.4 was this.

How is that extension N2Go meant to work then?
Should I completely deinstall and re-install, but an update should be OK I guess...?

**Comment by richardhj** [comment]
This extension does not provide any frontend module. It is meant to synchronize the members with Newsletter2Go, so whenever you edit a member in the back end, it'll be added to Newsletter2Go (once configured).
For your purpose, I recommend to use the html snippets provided by Newsletter2Go.

**Comment by richardhj** [comment]
Closing since the original issue is fixed.
